defmodule NotifierClient.Publisher do
  @moduledoc """
  Behaviour for publishing already encoded Notifier command payloads.

  `NotifierClient.deliver/2` and `NotifierClient.send_email/2` validate and
  serialize commands before calling the configured publisher. The publisher
  receives the JSON payload and transport options generated by the client, such
  as the RabbitMQ exchange and routing key.

  Production use defaults to `NotifierClient.Publisher.Tackle`. Tests can use
  `NotifierClient.Publisher.Stub` to capture publish calls without RabbitMQ.

      config :notifier_client_ex,
        publisher: NotifierClient.Publisher.Stub
  """

  @typedoc "JSON payload generated by the configured `NotifierClient.JSONCodec`."
  @type payload :: binary()

  @typedoc "Transport-specific options generated by NotifierClient."
  @type options :: keyword()

  @typedoc "Publisher result returned unchanged by the delivery APIs."
  @type result :: :ok | {:error, term()}

  @doc """
  Publishes a serialized Notifier command payload.

  Implementations should return `:ok` on success or `{:error, reason}` when the
  payload could not be published.
  """
  @callback publish(payload(), options()) :: result()
end
